### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by sgon00** [zarathir/lapce-markdown#1]
Sorry to post here. 
There is no readme and doc.
After installing this plugin, I don't see any differneces when opening a markdown file.
So I am really wondering what this plugin does.
Thanks a lot.

**Comment by zarathir** [comment]
It starts Marksman.

To quote the Marksman [repo](https://github.com/artempyanykh/marksman):
> Marksman is a program that integrates with your editor to assist you in writing and maintaining your Markdown documents. Using [LSP protocol](https://microsoft.github.io/language-server-protocol/) it provides completion, goto definition, find references, rename refactoring, diagnostics, and more. In addition to regular Markdown, it also supports wiki-link-style references that enable [Zettelkasten-like](https://en.wikipedia.org/wiki/Zettelkasten)[1](https://github.com/artempyanykh/marksman#user-content-fn-roam-research-58c45b60ea88920fcf52d1915870cedc), [2](https://github.com/artempyanykh/marksman#user-content-fn-markdown-memo-58c45b60ea88920fcf52d1915870cedc) note taking. See more about Marksman's features below.

> Marksman works on MacOS, Linux, and Windows and is distributed as a self-contained binary for each OS.

> The server provides assistance with:

    Markdown inline links:

    This is [inline link](/some-file.md#some-heading).
    This is an internal [anchor link](#heading).

    Markdown reference links:

    See [reference].

    [reference]: /url "Title"

    Wiki-links:

    Link to [[another-note]].
    Link to [[another-notes#heading]].
    Internal link to [[#a-heading]].

> All types of links support completion, hover, goto definition/references. Additionally, Marksman provides diagnostics for wiki-links to detect broken references and duplicate/ambiguous headings.

**Comment by sgon00** [comment]
Thank you very much for your response.
I will close this issue now.
Btw, do you plan to support markdown preview in the near future? (similar to vscode markdown preview or typora).

**Comment by zarathir** [comment]
> Btw, do you plan to support markdown preview in the near future? (similar to vscode markdown preview or typora).

That would be a nice feature. As of now Lapce lacks support for something like this. I think Markdown preview is baked into Vscode, so we'll have to see how this will get implemented in Lapce. But it's certainly something I'd like to have as well :)
